Repository 9oormthon-univ/2025_SEASONTHON_TEAM_2_BE, pull requests merged in 2025-09, with the labels that each got.

#12 Feat#7 오늘의 질문 api 구현
  src/main/java/com/seasonthon/everflow/app/appointment/domain/AcceptStatus.java
  src/main/java/com/seasonthon/everflow/app/appointment/domain/Appointment.java
  src/main/java/com/seasonthon/everflow/app/global/code/status/ErrorStatus.java
  src/main/java/com/seasonthon/everflow/app/global/exception/handler/ExceptionAdvice.java
  src/main/java/com/seasonthon/everflow/app/global/oauth/service/AuthService.java
  src/main/java/com/seasonthon/everflow/app/home/controller/HomeController.java
  src/main/java/com/seasonthon/everflow/app/home/dto/HomeDto.java
  src/main/java/com/seasonthon/everflow/app/home/service/HomeService.java
  src/main/java/com/seasonthon/everflow/app/topic/controller/TopicController.java
  src/main/java/com/seasonthon/everflow/app/topic/domain/Topic.java
  src/main/java/com/seasonthon/everflow/app/topic/domain/TopicAnswer.java
  src/main/java/com/seasonthon/everflow/app/topic/domain/TopicStatus.java
  src/main/java/com/seasonthon/everflow/app/topic/dto/TopicDto.java
  src/main/java/com/seasonthon/everflow/app/topic/repository/TopicAnswerRepository.java
  src/main/java/com/seasonthon/everflow/app/topic/repository/TopicRepository.java
  src/main/java/com/seasonthon/everflow/app/topic/scheduler/TopicScheduler.java
  src/main/java/com/seasonthon/everflow/app/topic/service/TopicService.java
  src/main/resources/application.yml
Labels: feature

#15 Feat#10 알림 관련 api 구현
  src/main/java/com/seasonthon/everflow/app/appointment/controller/AppointmentController.java
  src/main/java/com/seasonthon/everflow/app/notification/controller/NotificationController.java
  src/main/java/com/seasonthon/everflow/app/notification/domain/Notification.java
  src/main/java/com/seasonthon/everflow/app/notification/domain/NotificationType.java
  src/main/java/com/seasonthon/everflow/app/notification/domain/ReadStatus.java
  src/main/java/com/seasonthon/everflow/app/notification/dto/NotificationResponseDto.java
  src/main/java/com/seasonthon/everflow/app/notification/repository/NotificationRepository.java
  src/main/java/com/seasonthon/everflow/app/notification/service/NotificationService.java
Labels: feature

#17 Feat#16 알림 등록 기능 구현
  src/main/java/com/seasonthon/everflow/app/appointment/service/AppointmentService.java
  src/main/java/com/seasonthon/everflow/app/family/service/FamilyService.java
  src/main/java/com/seasonthon/everflow/app/notification/service/NotificationService.java
  src/main/java/com/seasonthon/everflow/app/topic/service/TopicService.java
Labels: feature

#26 Feat#14
  build.gradle
  src/main/java/com/seasonthon/everflow/EverflowApplication.java
  src/main/java/com/seasonthon/everflow/app/gemini/config/GeminiConfig.java
  src/main/java/com/seasonthon/everflow/app/gemini/config/GeminiInterface.java
  src/main/java/com/seasonthon/everflow/app/gemini/dto/GeminiRequestDto.java
  src/main/java/com/seasonthon/everflow/app/gemini/dto/GeminiResponseDto.java
  src/main/java/com/seasonthon/everflow/app/gemini/service/GeminiService.java
  src/main/java/com/seasonthon/everflow/app/global/code/status/ErrorStatus.java
  src/main/java/com/seasonthon/everflow/app/home/controller/HomeController.java
  src/main/java/com/seasonthon/everflow/app/home/dto/HomeDto.java
  src/main/java/com/seasonthon/everflow/app/topic/controller/TopicController.java
  src/main/java/com/seasonthon/everflow/app/topic/domain/Topic.java
  src/main/java/com/seasonthon/everflow/app/topic/domain/TopicType.java
  src/main/java/com/seasonthon/everflow/app/topic/dto/TopicDto.java
  src/main/java/com/seasonthon/everflow/app/topic/repository/TopicRepository.java
  src/main/java/com/seasonthon/everflow/app/topic/scheduler/TopicExpiryScheduler.java
  src/main/java/com/seasonthon/everflow/app/topic/scheduler/TopicScheduler.java
  src/main/java/com/seasonthon/everflow/app/topic/service/TopicService.java
  src/main/resources/application.yml
Labels: feature

#29 Feat#20 ProfileImageUpload 관련 코드
  src/main/java/com/seasonthon/everflow/app/s3/config/S3Config.java
  src/main/java/com/seasonthon/everflow/app/s3/service/S3Service.java
  src/main/java/com/seasonthon/everflow/app/user/controller/UserController.java
  src/main/java/com/seasonthon/everflow/app/user/domain/User.java
  src/main/java/com/seasonthon/everflow/app/user/dto/ProfileImageUploadDto.java
  src/main/java/com/seasonthon/everflow/app/user/dto/UserProfileImageResponseDto.java
  src/main/java/com/seasonthon/everflow/app/user/service/UserService.java
Labels: feature

#30 feat#21 / S3Config 업데이트
  src/main/java/com/seasonthon/everflow/app/s3/config/S3Config.java
Labels: bug

#40 fix#39 FamilyController에 가족코드를 조회하는 api 추가
  src/main/java/com/seasonthon/everflow/app/bookshelf/controller/BookshelfController.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/domain/BookshelfQuestion.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/repository/BookshelfQuestionRepository.java
  src/main/java/com/seasonthon/everflow/app/family/controller/FamilyController.java
  src/main/java/com/seasonthon/everflow/app/family/repository/FamilyRepository.java
  src/main/java/com/seasonthon/everflow/app/family/service/FamilyService.java
Labels: feature

#42 fix#41 미사용 글로벌 익셉션 코드 제거
  src/main/java/com/seasonthon/everflow/app/global/code/status/ErrorStatus.java
Labels: enhancement

#43 fix#40 가족 조회 API 요청사항 반영 수정
  src/main/java/com/seasonthon/everflow/app/family/controller/FamilyController.java
  src/main/java/com/seasonthon/everflow/app/family/dto/FamilyVerificationDetailResponseDto.java
  src/main/java/com/seasonthon/everflow/app/family/service/FamilyService.java
  src/main/java/com/seasonthon/everflow/app/global/security/SecurityConfig.java
Labels: enhancement, feature

#45 Feat#44 메모 api 구현
  src/main/java/com/seasonthon/everflow/app/family/service/FamilyService.java
  src/main/java/com/seasonthon/everflow/app/global/code/status/ErrorStatus.java
  src/main/java/com/seasonthon/everflow/app/memo/controller/MemoController.java
  src/main/java/com/seasonthon/everflow/app/memo/domain/Memo.java
  src/main/java/com/seasonthon/everflow/app/memo/dto/MemoDto.java
  src/main/java/com/seasonthon/everflow/app/memo/dto/MemoMapper.java
  src/main/java/com/seasonthon/everflow/app/memo/dto/UpdateMemoRequestDto.java
  src/main/java/com/seasonthon/everflow/app/memo/repository/MemoRepository.java
  src/main/java/com/seasonthon/everflow/app/memo/service/MemoService.java
Labels: feature

#49 Refactor#48 커스텀 가족 질문과 기본 질문 enum으로 구분하도록 리팩토링
  src/main/java/com/seasonthon/everflow/app/bookshelf/config/DefaultBookshelfSeeder.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/controller/BookshelfController.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/domain/BookshelfQuestion.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/domain/CustomBookshelfAnswer.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/domain/CustomBookshelfQuestion.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/domain/QuestionScope.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/dto/BookshelfAnswersUpsertRequestDto.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/repository/BookshelfQuestionRepository.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/repository/CustomBookshelfAnswerRepository.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/repository/CustomBookshelfQuestionRepository.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/service/BookshelfService.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/service/CustomBookshelfService.java
Labels: feature

#54 Bug#53 커스텀 가족 책장 질문 로직 수정
  src/main/java/com/seasonthon/everflow/app/bookshelf/repository/BookshelfAnswerRepository.java
  src/main/java/com/seasonthon/everflow/app/bookshelf/service/BookshelfService.java
Labels: bug

#61 Refactor#50 Gemini 프롬프트 수정 및 오늘의 질문 스케쥴러 수정
  src/main/java/com/seasonthon/everflow/app/gemini/config/GeminiConfig.java
  src/main/java/com/seasonthon/everflow/app/gemini/dto/GeminiRequestDto.java
  src/main/java/com/seasonthon/everflow/app/gemini/service/GeminiService.java
  src/main/java/com/seasonthon/everflow/app/topic/controller/TopicController.java
  src/main/java/com/seasonthon/everflow/app/topic/domain/Topic.java
  src/main/java/com/seasonthon/everflow/app/topic/domain/TopicAnswer.java
  src/main/java/com/seasonthon/everflow/app/topic/repository/TopicAnswerRepository.java
  src/main/java/com/seasonthon/everflow/app/topic/repository/TopicRepository.java
  src/main/java/com/seasonthon/everflow/app/topic/scheduler/GeminiTopicScheduler.java
  src/main/java/com/seasonthon/everflow/app/topic/scheduler/TopicExpiryScheduler.java
  src/main/java/com/seasonthon/everflow/app/topic/scheduler/TopicScheduler.java
  src/main/java/com/seasonthon/everflow/app/topic/service/TopicService.java
Labels: bug

#67 Bug#65 : BaseTimeEntity 써서 오늘의 질문 답변 최신순으로 정렬
  src/main/java/com/seasonthon/everflow/app/global/domain/BaseTimeEntity.java
  src/main/java/com/seasonthon/everflow/app/memo/controller/MemoController.java
  src/main/java/com/seasonthon/everflow/app/memo/service/MemoService.java
  src/main/java/com/seasonthon/everflow/app/topic/controller/TopicController.java
  src/main/java/com/seasonthon/everflow/app/topic/domain/TopicAnswer.java
  src/main/java/com/seasonthon/everflow/app/topic/repository/TopicAnswerRepository.java
  src/main/java/com/seasonthon/everflow/app/topic/service/TopicService.java
Labels: bug

#69 bug#68 : SSE를 위한 접근 설정 변경
  src/main/java/com/seasonthon/everflow/app/global/security/JwtAuthenticationProcessingFilter.java
  src/main/java/com/seasonthon/everflow/app/global/security/SecurityConfig.java
  src/main/java/com/seasonthon/everflow/app/notification/service/NotificationService.java
  src/main/java/com/seasonthon/everflow/app/s3/controller/FileController.java
Labels: bug
